server:
  port: 8080

spring:
  application:
    name: ec-system
  datasource:
    url: jdbc:mysql://49.232.196.48:3306/ec_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 49.232.196.48
      port: 6379
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

app:
  settlement:
    cron: 0 0 2 * * *
  rocketmq:
    enabled: false
    order-completed-topic: order-completed-topic

rocketmq:
  name-server: 49.232.196.48:9876
  producer:
    group: ec-system-producer-group
